name: QA_Practice_tests


on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: first test
        run: pytest tests/test_input_page.py::TestInputPage::test_name_input_field
      - name: second test
        run: pytest tests/test_input_page.py::TestInputPage::test_email_input_field
      - name: third test
        run: pytest tests/test_input_page.py::TestInputPage::test_password_input_field